import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#F3F7FA',
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 28,
    paddingTop: 28,
    paddingBottom: 32,
  },
  title: {
    fontSize: 34,
    fontWeight: '800',
    color: '#132238',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: '#678091',
    lineHeight: 24,
    marginBottom: 26,
  },
  formCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 30,
    padding: 26,
    shadowColor: '#A7BAC4',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.08,
    shadowRadius: 22,
    elevation: 4,
  },
  label: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1C3447',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#F8FBFC',
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 15,
    fontSize: 15,
    color: '#132238',
    borderWidth: 1,
    borderColor: '#DDE8EE',
    marginBottom: 18,
  },
  textArea: {
    minHeight: 120,
  },
  serviceTypeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 18,
  },
  serviceTypeOption: {
    minWidth: 110,
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderRadius: 18,
    backgroundColor: '#F8FBFC',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#DDE8EE',
  },
  serviceTypeOptionSelected: {
    backgroundColor: '#67AEB8',
    borderColor: '#67AEB8',
  },
  serviceTypeOptionText: {
    color: '#36566F',
    fontSize: 14,
    fontWeight: '800',
  },
  serviceTypeOptionTextSelected: {
    color: '#FFFFFF',
  },
  actions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  secondaryButton: {
    flex: 1,
    borderRadius: 18,
    paddingVertical: 15,
    alignItems: 'center',
    backgroundColor: '#F3F7FA',
    borderWidth: 1,
    borderColor: '#DDE8EE',
  },
  secondaryButtonText: {
    color: '#36566F',
    fontSize: 15,
    fontWeight: '800',
  },
  primaryButton: {
    flex: 1,
    borderRadius: 18,
    paddingVertical: 15,
    alignItems: 'center',
    backgroundColor: '#67AEB8',
    shadowColor: '#93C5CC',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
    elevation: 3,
  },
  primaryButtonDisabled: {
    opacity: 0.7,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
});
