import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#F4F7FB',
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 36,
    paddingBottom: 32,
  },
  title: {
    fontSize: 30,
    fontWeight: '700',
    color: '#132238',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: '#526071',
    lineHeight: 24,
    marginBottom: 26,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 22,
    shadowColor: '#132238',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 4,
    marginBottom: 18,
  },
  row: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  input: {
    flex: 1,
    backgroundColor: '#EEF3F8',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: '#132238',
  },
  primaryButton: {
    backgroundColor: '#2C8C99',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonDisabled: {
    opacity: 0.7,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  secondaryButton: {
    backgroundColor: '#DCEAF4',
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: '#29455C',
    fontSize: 15,
    fontWeight: '700',
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#132238',
    marginBottom: 16,
  },
  fieldBlock: {
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E7EDF5',
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#526071',
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  fieldValue: {
    fontSize: 16,
    color: '#132238',
    lineHeight: 24,
  },
  statusBox: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
    backgroundColor: '#F4F7FB',
    borderRadius: 18,
  },
  statusText: {
    marginTop: 12,
    fontSize: 15,
    color: '#526071',
    textAlign: 'center',
    lineHeight: 22,
  },
  errorText: {
    fontSize: 15,
    color: '#B42318',
    textAlign: 'center',
    lineHeight: 22,
  },
  itemCard: {
    backgroundColor: '#F9FBFD',
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E0E8F0',
    marginBottom: 14,
  },
  itemTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#132238',
    marginBottom: 8,
  },
  itemDescription: {
    fontSize: 14,
    color: '#526071',
    lineHeight: 22,
    marginBottom: 12,
  },
  metaText: {
    fontSize: 14,
    color: '#2C8C99',
    fontWeight: '700',
    marginBottom: 10,
  },
  actionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 14,
  },
  flexButton: {
    flex: 1,
    minWidth: 140,
  },
});
