import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#F3F7FA',
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 28,
    paddingTop: 28,
    paddingBottom: 32,
  },
  title: {
    fontSize: 34,
    fontWeight: '800',
    color: '#132238',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: '#678091',
    lineHeight: 24,
    marginBottom: 26,
  },
  heroBanner: {
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 28,
    marginBottom: 22,
    backgroundColor: '#EEF6F8',
    paddingHorizontal: 24,
    paddingVertical: 26,
    borderWidth: 1,
    borderColor: '#D9E8ED',
  },
  heroAccent: {
    position: 'absolute',
    top: -26,
    right: -10,
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: '#ADD5DA',
    opacity: 0.45,
  },
  heroContent: {
    maxWidth: 640,
  },
  heroEyebrow: {
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: '#4E8892',
    marginBottom: 10,
  },
  heroTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#1B374A',
    marginBottom: 10,
  },
  heroDescription: {
    fontSize: 15,
    lineHeight: 24,
    color: '#5D7789',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 30,
    padding: 24,
    shadowColor: '#A7BAC4',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.08,
    shadowRadius: 22,
    elevation: 4,
    marginBottom: 20,
  },
  row: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
  },
  input: {
    flex: 1,
    backgroundColor: '#F8FBFC',
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 15,
    fontSize: 15,
    color: '#132238',
    borderWidth: 1,
    borderColor: '#DDE8EE',
  },
  primaryButton: {
    backgroundColor: '#67AEB8',
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#93C5CC',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
    elevation: 3,
  },
  primaryButtonDisabled: {
    opacity: 0.7,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  secondaryButton: {
    backgroundColor: '#F3F7FA',
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#DDE8EE',
  },
  secondaryButtonText: {
    color: '#36566F',
    fontSize: 15,
    fontWeight: '800',
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#132238',
    marginBottom: 16,
  },
  fieldBlock: {
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E7EEF2',
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: '#678091',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  fieldValue: {
    fontSize: 16,
    color: '#1E3347',
    lineHeight: 24,
  },
  statusBox: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
    backgroundColor: '#F8FBFC',
    borderRadius: 22,
  },
  statusText: {
    marginTop: 12,
    fontSize: 15,
    color: '#627C8E',
    textAlign: 'center',
    lineHeight: 22,
  },
  errorText: {
    fontSize: 15,
    color: '#B42318',
    textAlign: 'center',
    lineHeight: 22,
  },
  successBox: {
    backgroundColor: '#EEF8F6',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#D7ECE7',
    marginBottom: 16,
  },
  successText: {
    fontSize: 15,
    color: '#4E8892',
    textAlign: 'center',
    fontWeight: '800',
    lineHeight: 22,
  },
  itemCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E2EBF0',
    marginBottom: 16,
    shadowColor: '#A7BAC4',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
    elevation: 2,
  },
  candidateTopRow: {
    marginBottom: 16,
  },
  candidateIdentityRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  candidatePhoto: {
    width: 76,
    height: 76,
    borderRadius: 24,
    backgroundColor: '#E0ECEF',
    marginRight: 16,
  },
  candidateAvatarFallback: {
    width: 76,
    height: 76,
    borderRadius: 24,
    backgroundColor: '#8CC0C7',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
    shadowColor: '#B4D8DD',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 3,
  },
  candidateAvatarText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: '800',
  },
  candidateTextBlock: {
    flex: 1,
  },
  itemTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#132238',
    marginBottom: 10,
  },
  candidateBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#EEF8F6',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  candidateBadgeText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#4E8892',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  candidateInfoPanel: {
    backgroundColor: '#F8FBFC',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#E2EBF0',
  },
  candidateInfoLabel: {
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    color: '#678091',
    marginBottom: 6,
  },
  itemDescription: {
    fontSize: 16,
    color: '#294055',
    lineHeight: 24,
    marginBottom: 0,
  },
  metaText: {
    fontSize: 14,
    color: '#5D9FA8',
    fontWeight: '800',
    marginBottom: 10,
  },
  actionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 14,
  },
  approveButton: {
    minWidth: 170,
    paddingVertical: 15,
    borderRadius: 18,
    shadowColor: '#93C5CC',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
    elevation: 3,
  },
  flexButton: {
    flex: 1,
    minWidth: 140,
  },
});
