import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#F4F7FB',
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 36,
    paddingBottom: 24,
  },
  title: {
    fontSize: 30,
    fontWeight: '700',
    color: '#132238',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: '#526071',
    lineHeight: 24,
    marginBottom: 26,
  },
  searchCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 22,
    shadowColor: '#132238',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 4,
    marginBottom: 18,
  },
  searchLabel: {
    fontSize: 16,
    fontWeight: '700',
    color: '#132238',
    marginBottom: 16,
  },
  searchRow: {
    gap: 14,
    marginBottom: 14,
  },
  searchInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EEF3F8',
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  searchIcon: {
    width: 22,
    height: 22,
    marginRight: 10,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchLens: {
    width: 13,
    height: 13,
    borderWidth: 2,
    borderColor: '#41556F',
    borderRadius: 7,
  },
  searchHandle: {
    width: 8,
    height: 2,
    backgroundColor: '#41556F',
    borderRadius: 2,
    position: 'absolute',
    right: 1,
    bottom: 3,
    transform: [{ rotate: '45deg' }],
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: '#132238',
    paddingVertical: 10,
  },
  addServiceButton: {
    backgroundColor: '#2C8C99',
    paddingHorizontal: 20,
    paddingVertical: 13,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addServiceButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
  },
  quickActionsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  secondaryActionButton: {
    backgroundColor: '#DCEAF4',
    paddingHorizontal: 20,
    paddingVertical: 13,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryActionButtonText: {
    color: '#29455C',
    fontSize: 15,
    fontWeight: '700',
  },
  infoCard: {
    backgroundColor: '#DCEAF4',
    borderRadius: 24,
    padding: 22,
    marginBottom: 18,
  },
  infoTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#132238',
    marginBottom: 8,
  },
  infoText: {
    fontSize: 15,
    color: '#3C4C61',
    lineHeight: 22,
  },
  servicesCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 22,
    shadowColor: '#132238',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 4,
  },
  servicesTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#132238',
    marginBottom: 18,
  },
  servicesStatusBox: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
    backgroundColor: '#F4F7FB',
    borderRadius: 18,
  },
  servicesStatusText: {
    marginTop: 12,
    fontSize: 15,
    color: '#526071',
  },
  servicesErrorText: {
    fontSize: 15,
    color: '#B42318',
    textAlign: 'center',
    lineHeight: 22,
  },
  serviceItem: {
    backgroundColor: '#F9FBFD',
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E0E8F0',
    marginBottom: 14,
  },
  serviceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginBottom: 10,
  },
  serviceItemTitle: {
    flex: 1,
    fontSize: 17,
    fontWeight: '700',
    color: '#132238',
  },
  serviceBadge: {
    backgroundColor: '#DCEAF4',
    color: '#29455C',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    fontSize: 12,
    fontWeight: '700',
    overflow: 'hidden',
  },
  serviceDescription: {
    fontSize: 14,
    color: '#526071',
    lineHeight: 21,
    marginBottom: 12,
  },
  serviceAmount: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2C8C99',
  },
  serviceStatus: {
    marginTop: 8,
    fontSize: 13,
    color: '#526071',
    fontWeight: '600',
  },
  serviceActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 14,
  },
  serviceActionButton: {
    flex: 1,
    minWidth: 130,
    backgroundColor: '#2C8C99',
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: 'center',
  },
  serviceActionButtonDisabled: {
    opacity: 0.65,
  },
  serviceActionButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  serviceSecondaryButton: {
    flex: 1,
    minWidth: 130,
    backgroundColor: '#DCEAF4',
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: 'center',
  },
  serviceSecondaryButtonText: {
    color: '#29455C',
    fontSize: 14,
    fontWeight: '700',
  },
});
