import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#F3F7FA',
  },
  content: {
    flexGrow: 1,
    paddingHorizontal: 28,
    paddingTop: 28,
    paddingBottom: 28,
  },
  title: {
    fontSize: 34,
    fontWeight: '800',
    color: '#132238',
    marginBottom: 10,
  },
  subtitle: {
    fontSize: 16,
    color: '#678091',
    lineHeight: 24,
    marginBottom: 26,
  },
  searchCard: {
    backgroundColor: '#EEF6F8',
    borderRadius: 30,
    padding: 24,
    borderWidth: 1,
    borderColor: '#D9E8ED',
    shadowColor: '#A7BAC4',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.09,
    shadowRadius: 20,
    elevation: 4,
    marginBottom: 20,
  },
  searchLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: '#4E8892',
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.9,
  },
  searchRow: {
    gap: 14,
    marginBottom: 14,
  },
  searchInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#DDE8EE',
  },
  searchIcon: {
    width: 22,
    height: 22,
    marginRight: 10,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchLens: {
    width: 13,
    height: 13,
    borderWidth: 2,
    borderColor: '#587086',
    borderRadius: 7,
  },
  searchHandle: {
    width: 8,
    height: 2,
    backgroundColor: '#587086',
    borderRadius: 2,
    position: 'absolute',
    right: 1,
    bottom: 3,
    transform: [{ rotate: '45deg' }],
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: '#132238',
    paddingVertical: 10,
  },
  addServiceButton: {
    backgroundColor: '#67AEB8',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#93C5CC',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.16,
    shadowRadius: 12,
    elevation: 3,
  },
  addServiceButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  quickActionsRow: {
    flexDirection: 'row',
    gap: 12,
  },
  secondaryActionButton: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#DDE8EE',
  },
  secondaryActionButtonText: {
    color: '#36566F',
    fontSize: 15,
    fontWeight: '800',
  },
  infoCard: {
    backgroundColor: '#F0F7F6',
    borderRadius: 28,
    padding: 22,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#DBECE7',
  },
  infoTitle: {
    fontSize: 19,
    fontWeight: '800',
    color: '#132238',
    marginBottom: 8,
  },
  infoText: {
    fontSize: 15,
    color: '#567082',
    lineHeight: 23,
  },
  servicesCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 30,
    padding: 24,
    shadowColor: '#A7BAC4',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.08,
    shadowRadius: 22,
    elevation: 4,
  },
  servicesTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#132238',
    marginBottom: 18,
  },
  servicesStatusBox: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 28,
    backgroundColor: '#F8FBFC',
    borderRadius: 22,
  },
  servicesStatusText: {
    marginTop: 12,
    fontSize: 15,
    color: '#627C8E',
  },
  servicesErrorText: {
    fontSize: 15,
    color: '#B42318',
    textAlign: 'center',
    lineHeight: 22,
  },
  serviceItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#E2EBF0',
    marginBottom: 16,
  },
  serviceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginBottom: 10,
  },
  serviceItemTitle: {
    flex: 1,
    fontSize: 19,
    fontWeight: '800',
    color: '#132238',
  },
  serviceBadge: {
    backgroundColor: '#EEF8F6',
    color: '#4E8892',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    fontSize: 12,
    fontWeight: '800',
    overflow: 'hidden',
  },
  serviceDescription: {
    fontSize: 15,
    color: '#5A7284',
    lineHeight: 23,
    marginBottom: 12,
  },
  serviceAmount: {
    fontSize: 18,
    fontWeight: '800',
    color: '#5D9FA8',
  },
  serviceStatus: {
    marginTop: 8,
    fontSize: 13,
    color: '#667F90',
    fontWeight: '700',
  },
  serviceActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 14,
  },
  serviceActionButton: {
    flex: 1,
    minWidth: 130,
    backgroundColor: '#67AEB8',
    borderRadius: 18,
    paddingVertical: 13,
    alignItems: 'center',
  },
  serviceActionButtonDisabled: {
    opacity: 0.65,
  },
  serviceActionButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  serviceSecondaryButton: {
    flex: 1,
    minWidth: 130,
    backgroundColor: '#F3F7FA',
    borderRadius: 18,
    paddingVertical: 13,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#DDE8EE',
  },
  serviceSecondaryButtonText: {
    color: '#36566F',
    fontSize: 14,
    fontWeight: '800',
  },
});
