import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: '#F3F7FA',
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 36,
    position: 'relative',
  },
  backgroundOrbPrimary: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    backgroundColor: '#E4F2F4',
    top: -60,
    right: -100,
  },
  backgroundOrbSecondary: {
    position: 'absolute',
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: '#E9EFF8',
    bottom: 120,
    left: -80,
  },
  heroCard: {
    backgroundColor: '#EDF6F8',
    borderRadius: 34,
    padding: 26,
    marginBottom: 26,
    borderWidth: 1,
    borderColor: '#D7E8EC',
    shadowColor: '#A8BBC5',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 5,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginBottom: 28,
    flexWrap: 'wrap',
  },
  brandPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#F8FCFD',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#DAEAEE',
  },
  brandPillText: {
    color: '#4F8790',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  heroActions: {
    flexDirection: 'row',
    gap: 12,
    flexWrap: 'wrap',
  },
  primaryButton: {
    backgroundColor: '#67AEB8',
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 14,
    shadowColor: '#9AC8CF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 3,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  secondaryButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#DDE8EE',
  },
  secondaryButtonText: {
    color: '#35556E',
    fontSize: 15,
    fontWeight: '800',
  },
  heroTitle: {
    color: '#1C374A',
    fontSize: 38,
    fontWeight: '800',
    lineHeight: 46,
    maxWidth: 780,
    marginBottom: 14,
  },
  heroSubtitle: {
    color: '#5F7A8C',
    fontSize: 17,
    lineHeight: 26,
    maxWidth: 760,
    marginBottom: 24,
  },
  heroStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 14,
  },
  heroStatCard: {
    minWidth: 150,
    backgroundColor: '#FAFCFD',
    borderRadius: 22,
    paddingHorizontal: 18,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: '#DCE9EE',
  },
  heroStatValue: {
    color: '#1E394B',
    fontSize: 26,
    fontWeight: '800',
    marginBottom: 4,
  },
  heroStatLabel: {
    color: '#6A8494',
    fontSize: 14,
    fontWeight: '700',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: 16,
    marginBottom: 20,
    flexWrap: 'wrap',
  },
  sectionEyebrow: {
    color: '#4E8892',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 6,
  },
  sectionTitle: {
    color: '#132238',
    fontSize: 30,
    fontWeight: '800',
  },
  refreshButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#DDE8EE',
  },
  refreshButtonText: {
    color: '#36566F',
    fontSize: 15,
    fontWeight: '800',
  },
  explanationCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 22,
    borderWidth: 1,
    borderColor: '#E2EBF0',
    marginBottom: 22,
    shadowColor: '#A8BBC5',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.07,
    shadowRadius: 22,
    elevation: 3,
  },
  explanationTitle: {
    color: '#132238',
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 10,
  },
  explanationText: {
    color: '#5B7284',
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 10,
  },
  statusCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 26,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#A8BBC5',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.08,
    shadowRadius: 22,
    elevation: 4,
  },
  statusText: {
    marginTop: 12,
    color: '#637D8F',
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
  },
  errorText: {
    color: '#B42318',
    fontSize: 15,
    textAlign: 'center',
    lineHeight: 22,
  },
  servicesGrid: {
    gap: 18,
  },
  serviceCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 28,
    padding: 22,
    borderWidth: 1,
    borderColor: '#E2EBF0',
    shadowColor: '#A8BBC5',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.07,
    shadowRadius: 22,
    elevation: 3,
  },
  serviceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
  },
  serviceTitle: {
    flex: 1,
    color: '#132238',
    fontSize: 22,
    fontWeight: '800',
  },
  serviceBadge: {
    backgroundColor: '#EEF8F6',
    color: '#4E8892',
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
    overflow: 'hidden',
    fontSize: 12,
    fontWeight: '800',
  },
  serviceDescription: {
    color: '#5B7284',
    fontSize: 15,
    lineHeight: 24,
    marginBottom: 16,
  },
  serviceMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginBottom: 16,
    flexWrap: 'wrap',
  },
  serviceAmount: {
    color: '#5E9FA8',
    fontSize: 18,
    fontWeight: '800',
  },
  serviceStatus: {
    color: '#687F90',
    fontSize: 14,
    fontWeight: '700',
  },
  serviceFooter: {
    backgroundColor: '#F8FBFC',
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E2EBF0',
  },
  serviceFooterText: {
    color: '#5E7688',
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 12,
  },
  cardActionButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#EAF2F5',
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#DAE7ED',
  },
  cardActionButtonText: {
    color: '#284B63',
    fontSize: 14,
    fontWeight: '800',
  },
});
