import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  sidebar: {
    width: 124,
    backgroundColor: '#F7FBFC',
    paddingHorizontal: 14,
    paddingTop: 24,
    paddingBottom: 20,
    justifyContent: 'space-between',
    borderTopRightRadius: 28,
    borderBottomRightRadius: 28,
    borderRightWidth: 1,
    borderColor: '#DEE9EE',
    shadowColor: '#B2C2CB',
    shadowOffset: { width: 8, height: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 4,
  },
  profileSection: {
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 16,
    paddingHorizontal: 10,
    borderWidth: 1,
    borderColor: '#E1EBF0',
  },
  profileSectionPressable: {
    borderRadius: 24,
  },
  avatar: {
    width: 62,
    height: 62,
    borderRadius: 22,
    backgroundColor: '#8CC0C7',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
    shadowColor: '#B4D8DD',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 3,
  },
  avatarText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: '800',
  },
  profileName: {
    color: '#1C3447',
    fontSize: 16,
    fontWeight: '800',
    textAlign: 'center',
  },
  profileRole: {
    color: '#718897',
    fontSize: 12,
    textAlign: 'center',
  },
  navigationSection: {
    gap: 10,
  },
  navItem: {
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 10,
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E1EBF0',
  },
  navItemActive: {
    backgroundColor: '#EEF8F6',
    borderColor: '#D7ECE7',
  },
  navIcon: {
    color: '#31526A',
    fontSize: 18,
    fontWeight: '800',
  },
  navText: {
    color: '#6D8595',
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  navTextActive: {
    color: '#4E8892',
  },
  logoutButton: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 15,
    borderRadius: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E1EBF0',
  },
  logoutButtonText: {
    color: '#35556E',
    fontSize: 15,
    fontWeight: '800',
  },
});
