import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3F7FA',
    justifyContent: 'center',
    paddingHorizontal: 24,
    alignSelf: 'center',
    width: '100%',
    maxWidth: 540,
    position: 'relative',
    overflow: 'hidden',
  },
  backgroundOrbPrimary: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: '#E5F3F5',
    top: 60,
    right: -70,
    opacity: 0.9,
  },
  backgroundOrbSecondary: {
    position: 'absolute',
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: '#E9EFF8',
    bottom: 70,
    left: -90,
  },
  authCard: {
    backgroundColor: '#FCFEFF',
    borderRadius: 30,
    paddingHorizontal: 26,
    paddingVertical: 28,
    borderWidth: 1,
    borderColor: '#DCE8EE',
    shadowColor: '#A7BAC4',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.1,
    shadowRadius: 24,
    elevation: 6,
  },
  brandPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#F7FBFC',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: '#DCE8EE',
  },
  brandPillText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#4E8892',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  headerSection: {
    marginBottom: 22,
  },
  title: {
    fontSize: 36,
    fontWeight: '800',
    color: '#1C3447',
    lineHeight: 42,
  },
  subtitle: {
    fontSize: 16,
    color: '#668091',
    marginTop: 10,
    lineHeight: 24,
  },
  highlightPanel: {
    backgroundColor: '#F1F7F9',
    borderRadius: 24,
    padding: 20,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: '#DCE8EE',
  },
  highlightEyebrow: {
    color: '#4E8892',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
  },
  highlightTitle: {
    color: '#1B374A',
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 26,
    marginBottom: 8,
  },
  highlightText: {
    color: '#60798A',
    fontSize: 14,
    lineHeight: 22,
  },
  input: {
    backgroundColor: '#F8FBFC',
    minHeight: 58,
    borderRadius: 18,
    paddingHorizontal: 18,
    fontSize: 16,
    color: '#183044',
    borderWidth: 1,
    borderColor: '#DDE8EE',
    marginBottom: 14,
  },
  button: {
    backgroundColor: '#67AEB8',
    minHeight: 58,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    shadowColor: '#93C5CC',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 14,
    elevation: 4,
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '800',
  },
  footerText: {
    textAlign: 'center',
    marginTop: 25,
    color: '#678090',
    fontSize: 14,
  },
  linkText: {
    color: '#4B8C96',
    fontWeight: '800',
  },
});
